version: '3.8'
services:
  quicksilver:
    image: quicksilverzone/quicksilver:latest
    hostname: quicksilver
    volumes:
      - ./data/test-1:/quicksilver/.quicksilverd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 26657:26657
      - 1317:1317
  quicksilver2:
    image: quicksilverzone/quicksilver:latest
    hostname: quicksilver2
    volumes:
      - ./data/test-1a:/quicksilver/.quicksilverd
    build:
      context: .
      dockerfile: Dockerfile
  quicksilver3:
    image: quicksilverzone/quicksilver:latest
    hostname: quicksilver3
    volumes:
      - ./data/test-1b:/quicksilver/.quicksilverd
    build:
      context: .
      dockerfile: Dockerfile
  testzone:
    image: quicksilverzone/testzone:latest
    hostname: testzone
    volumes:
      - ./data/test-2:/icad/.ica
    command:
      - icad
      - start
  testzone2:
    image: quicksilverzone/testzone:latest
    hostname: testzone2
    volumes:
      - ./data/test-2a:/icad/.ica
    command:
      - icad
      - start
  testzone3:
    image: quicksilverzone/testzone:latest
    hostname: testzone3
    volumes:
      - ./data/test-2b:/icad/.ica
    command:
      - icad
      - start
  testzone4:
    image: quicksilverzone/testzone:latest
    hostname: testzone4
    volumes:
      - ./data/test-2c:/icad/.ica
    command:
      - icad
      - start
  hermes:
    image: quicksilverzone/hermes
    hostname: hermes
    volumes:
      - ./scripts/config/hermes.toml:/tmp/hermes.toml
      - ./data/hermes:/hermes/.hermes
    command:
      - hermes
      - -c
      - /tmp/hermes.toml
      - start
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.hermes
  icq:
    image: quicksilverzone/interchain-queries:v0.2.0
    volumes:
      - ./data/icq:/icq/.icq
    command:
      - interchain-queries
      - run
    restart: always
